#!/bin/sh

cd ~/workspace/discordBotNodeJS

git pull origin master

curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash

. ~/.nvm/nvm.sh
nvm install v10.11.0
npm install
pm2 restart ecosystem.config.js
